### ISSUE TITLE
Is it reasonable to infer the average value of 1, 5, and 15 minutes based on the obtained two values

### ISSUE THREAD

**Issue by 21pages** [oraclerob/uptime#1]
![image](https://github.com/oraclerob/uptime/assets/14891774/0c6b5ee4-6ee0-4496-96ac-319cf49fb0b6)
and the CPU usage is significantly smaller than that displayed by taskManager.

**Comment by oraclerob** [comment]
This is the way all Unix uptimes are calculated. Using 2 time values and a mathematical function to infer the 1/5/15 minute load averages. I'm not saying it is accurate, nor is the windows call underneath. I'm just displaying what I'm receiving.
